### ISSUE TITLE
Add auto-save

### ISSUE THREAD

**Issue by miapuffia** [ToniMacaroni/ModdingEx#1]
This plugin is a life saver but it's annoying that packaging manually doesn't require I save all assets (ctrl + shift + s) but building the mod does. Can this be added as an option in the settings? Thanks

**Comment by ToniMacaroni** [comment]
Sure!

**Comment by ToniMacaroni** [comment]
The [1.1.0 release](https://github.com/ToniMacaroni/ModdingEx/releases/tag/1.1.0) now has the option to save all packages before building a mod.
